//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.18 at 02:08:56 PM IST 
//


package com.eca.cme.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classTriggerActnCnfgType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="classTriggerActnCnfgType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="db-sql-syntax" type="{}dbSqlSyntaxType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="triggering-event" use="required" type="{}triggeringEventType" />
 *       &lt;attribute name="trigger-type" use="required" type="{}triggerTypeType" />
 *       &lt;attribute name="sort-order" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="description" type="{}descriptionType" />
 *       &lt;attribute name="disabled-ind" type="{}indicatorType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "classTriggerActnCnfgType", propOrder = {
    "dbSqlSyntax"
})
public class ClassTriggerActnCnfgType {

    @XmlElement(name = "db-sql-syntax", required = true)
    protected String dbSqlSyntax;
    @XmlAttribute(name = "triggering-event", required = true)
    protected String triggeringEvent;
    @XmlAttribute(name = "trigger-type", required = true)
    protected TriggerTypeType triggerType;
    @XmlAttribute(name = "sort-order", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sortOrder;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "disabled-ind")
    protected IndicatorType disabledInd;

    /**
     * Gets the value of the dbSqlSyntax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbSqlSyntax() {
        return dbSqlSyntax;
    }

    /**
     * Sets the value of the dbSqlSyntax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbSqlSyntax(String value) {
        this.dbSqlSyntax = value;
    }

    /**
     * Gets the value of the triggeringEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggeringEvent() {
        return triggeringEvent;
    }

    /**
     * Sets the value of the triggeringEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggeringEvent(String value) {
        this.triggeringEvent = value;
    }

    /**
     * Gets the value of the triggerType property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerTypeType }
     *     
     */
    public TriggerTypeType getTriggerType() {
        return triggerType;
    }

    /**
     * Sets the value of the triggerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerTypeType }
     *     
     */
    public void setTriggerType(TriggerTypeType value) {
        this.triggerType = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSortOrder(BigInteger value) {
        this.sortOrder = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the disabledInd property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorType }
     *     
     */
    public IndicatorType getDisabledInd() {
        return disabledInd;
    }

    /**
     * Sets the value of the disabledInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorType }
     *     
     */
    public void setDisabledInd(IndicatorType value) {
        this.disabledInd = value;
    }

}
