//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.18 at 02:08:56 PM IST 
//


package com.eca.cme.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classRefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="classRefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="app-space-cntx " type="{}appSpaceCntxElementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="owner-cntx" type="{}ownerCntxElementType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="class-name" use="required" type="{}classNameType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "classRefType", propOrder = {
    "appSpaceCntx0020",
    "ownerCntx"
})
public class ClassRefType {

    @XmlElement(name = "app-space-cntx")
    protected List<AppSpaceCntxElementType> appSpaceCntx0020;
    @XmlElement(name = "owner-cntx")
    protected List<OwnerCntxElementType> ownerCntx;
    @XmlAttribute(name = "class-name", required = true)
    protected String className;

    /**
     * Gets the value of the appSpaceCntx0020 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appSpaceCntx0020 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppSpaceCntx_0020().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AppSpaceCntxElementType }
     * 
     * 
     */
    public List<AppSpaceCntxElementType> getAppSpaceCntx_0020() {
        if (appSpaceCntx0020 == null) {
            appSpaceCntx0020 = new ArrayList<AppSpaceCntxElementType>();
        }
        return this.appSpaceCntx0020;
    }

    /**
     * Gets the value of the ownerCntx property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ownerCntx property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnerCntx().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OwnerCntxElementType }
     * 
     * 
     */
    public List<OwnerCntxElementType> getOwnerCntx() {
        if (ownerCntx == null) {
            ownerCntx = new ArrayList<OwnerCntxElementType>();
        }
        return this.ownerCntx;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

}
