//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.18 at 02:08:56 PM IST 
//


package com.eca.cme.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classCnfgType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="classCnfgType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="db-where-condition" type="{}propertyValueType" minOccurs="0"/>
 *         &lt;element name="app-space-cntx " type="{}appSpaceCntxElementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="owner-cntx" type="{}ownerCntxElementType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="class-name" use="required" type="{}classNameType" />
 *       &lt;attribute name="class-type" use="required" type="{}classTypeType" />
 *       &lt;attribute name="time-scope-code" type="{}timeScopeCodeType" />
 *       &lt;attribute name="owner-class-name" type="{}classNameType" />
 *       &lt;attribute name="db-object-type" type="{}dbObjectTypeType" />
 *       &lt;attribute name="db-object-owner" type="{}dbObjectNameType" />
 *       &lt;attribute name="db-object-name" type="{}dbObjectNameType" />
 *       &lt;attribute name="db-object-attribute" type="{}dbObjectNameType" />
 *       &lt;attribute name="app-space-cntx" use="required" type="{}cntxtType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "classCnfgType", propOrder = {
    "dbWhereCondition",
    "appSpaceCntx0020",
    "ownerCntx"
})
public class ClassCnfgType {

    @XmlElement(name = "db-where-condition")
    protected String dbWhereCondition;
    @XmlElement(name = "app-space-cntx")
    protected List<AppSpaceCntxElementType> appSpaceCntx0020;
    @XmlElement(name = "owner-cntx")
    protected List<OwnerCntxElementType> ownerCntx;
    @XmlAttribute(name = "class-name", required = true)
    protected String className;
    @XmlAttribute(name = "class-type", required = true)
    protected ClassTypeType classType;
    @XmlAttribute(name = "time-scope-code")
    protected String timeScopeCode;
    @XmlAttribute(name = "owner-class-name")
    protected String ownerClassName;
    @XmlAttribute(name = "db-object-type")
    protected DbObjectTypeType dbObjectType;
    @XmlAttribute(name = "db-object-owner")
    protected String dbObjectOwner;
    @XmlAttribute(name = "db-object-name")
    protected String dbObjectName;
    @XmlAttribute(name = "db-object-attribute")
    protected String dbObjectAttribute;
    @XmlAttribute(name = "app-space-cntx", required = true)
    protected String appSpaceCntx;

    /**
     * Gets the value of the dbWhereCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbWhereCondition() {
        return dbWhereCondition;
    }

    /**
     * Sets the value of the dbWhereCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbWhereCondition(String value) {
        this.dbWhereCondition = value;
    }

    /**
     * Gets the value of the appSpaceCntx0020 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appSpaceCntx0020 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppSpaceCntx_0020().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AppSpaceCntxElementType }
     * 
     * 
     */
    public List<AppSpaceCntxElementType> getAppSpaceCntx_0020() {
        if (appSpaceCntx0020 == null) {
            appSpaceCntx0020 = new ArrayList<AppSpaceCntxElementType>();
        }
        return this.appSpaceCntx0020;
    }

    /**
     * Gets the value of the ownerCntx property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ownerCntx property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnerCntx().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OwnerCntxElementType }
     * 
     * 
     */
    public List<OwnerCntxElementType> getOwnerCntx() {
        if (ownerCntx == null) {
            ownerCntx = new ArrayList<OwnerCntxElementType>();
        }
        return this.ownerCntx;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the classType property.
     * 
     * @return
     *     possible object is
     *     {@link ClassTypeType }
     *     
     */
    public ClassTypeType getClassType() {
        return classType;
    }

    /**
     * Sets the value of the classType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassTypeType }
     *     
     */
    public void setClassType(ClassTypeType value) {
        this.classType = value;
    }

    /**
     * Gets the value of the timeScopeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeScopeCode() {
        return timeScopeCode;
    }

    /**
     * Sets the value of the timeScopeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeScopeCode(String value) {
        this.timeScopeCode = value;
    }

    /**
     * Gets the value of the ownerClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerClassName() {
        return ownerClassName;
    }

    /**
     * Sets the value of the ownerClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerClassName(String value) {
        this.ownerClassName = value;
    }

    /**
     * Gets the value of the dbObjectType property.
     * 
     * @return
     *     possible object is
     *     {@link DbObjectTypeType }
     *     
     */
    public DbObjectTypeType getDbObjectType() {
        return dbObjectType;
    }

    /**
     * Sets the value of the dbObjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbObjectTypeType }
     *     
     */
    public void setDbObjectType(DbObjectTypeType value) {
        this.dbObjectType = value;
    }

    /**
     * Gets the value of the dbObjectOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbObjectOwner() {
        return dbObjectOwner;
    }

    /**
     * Sets the value of the dbObjectOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbObjectOwner(String value) {
        this.dbObjectOwner = value;
    }

    /**
     * Gets the value of the dbObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbObjectName() {
        return dbObjectName;
    }

    /**
     * Sets the value of the dbObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbObjectName(String value) {
        this.dbObjectName = value;
    }

    /**
     * Gets the value of the dbObjectAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbObjectAttribute() {
        return dbObjectAttribute;
    }

    /**
     * Sets the value of the dbObjectAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbObjectAttribute(String value) {
        this.dbObjectAttribute = value;
    }

    /**
     * Gets the value of the appSpaceCntx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppSpaceCntx() {
        return appSpaceCntx;
    }

    /**
     * Sets the value of the appSpaceCntx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppSpaceCntx(String value) {
        this.appSpaceCntx = value;
    }

}
