//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.18 at 02:08:56 PM IST 
//


package com.eca.cme.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eca.cme.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClassXml_QNAME = new QName("", "class-xml");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eca.cme.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassXmlType }
     * 
     */
    public ClassXmlType createClassXmlType() {
        return new ClassXmlType();
    }

    /**
     * Create an instance of {@link ClassRelationRefType }
     * 
     */
    public ClassRelationRefType createClassRelationRefType() {
        return new ClassRelationRefType();
    }

    /**
     * Create an instance of {@link ClassDependencyCnfgType }
     * 
     */
    public ClassDependencyCnfgType createClassDependencyCnfgType() {
        return new ClassDependencyCnfgType();
    }

    /**
     * Create an instance of {@link ClassTraPropertyCnfgType }
     * 
     */
    public ClassTraPropertyCnfgType createClassTraPropertyCnfgType() {
        return new ClassTraPropertyCnfgType();
    }

    /**
     * Create an instance of {@link OwnerCntxElementType }
     * 
     */
    public OwnerCntxElementType createOwnerCntxElementType() {
        return new OwnerCntxElementType();
    }

    /**
     * Create an instance of {@link ClassRefType }
     * 
     */
    public ClassRefType createClassRefType() {
        return new ClassRefType();
    }

    /**
     * Create an instance of {@link ClassAttributeRefType }
     * 
     */
    public ClassAttributeRefType createClassAttributeRefType() {
        return new ClassAttributeRefType();
    }

    /**
     * Create an instance of {@link ClassCnfgType }
     * 
     */
    public ClassCnfgType createClassCnfgType() {
        return new ClassCnfgType();
    }

    /**
     * Create an instance of {@link ClassRelationCnfgType }
     * 
     */
    public ClassRelationCnfgType createClassRelationCnfgType() {
        return new ClassRelationCnfgType();
    }

    /**
     * Create an instance of {@link ClassRelPropertyCnfgType }
     * 
     */
    public ClassRelPropertyCnfgType createClassRelPropertyCnfgType() {
        return new ClassRelPropertyCnfgType();
    }

    /**
     * Create an instance of {@link ClassAttrPropertyCnfgType }
     * 
     */
    public ClassAttrPropertyCnfgType createClassAttrPropertyCnfgType() {
        return new ClassAttrPropertyCnfgType();
    }

    /**
     * Create an instance of {@link AppSpaceCntxElementType }
     * 
     */
    public AppSpaceCntxElementType createAppSpaceCntxElementType() {
        return new AppSpaceCntxElementType();
    }

    /**
     * Create an instance of {@link ClassTriggerActnCnfgType }
     * 
     */
    public ClassTriggerActnCnfgType createClassTriggerActnCnfgType() {
        return new ClassTriggerActnCnfgType();
    }

    /**
     * Create an instance of {@link ClassPropertyCnfgType }
     * 
     */
    public ClassPropertyCnfgType createClassPropertyCnfgType() {
        return new ClassPropertyCnfgType();
    }

    /**
     * Create an instance of {@link ClassAttributeCnfgType }
     * 
     */
    public ClassAttributeCnfgType createClassAttributeCnfgType() {
        return new ClassAttributeCnfgType();
    }

    /**
     * Create an instance of {@link ClassTriggerActnRefType }
     * 
     */
    public ClassTriggerActnRefType createClassTriggerActnRefType() {
        return new ClassTriggerActnRefType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassXmlType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "class-xml")
    public JAXBElement<ClassXmlType> createClassXml(ClassXmlType value) {
        return new JAXBElement<ClassXmlType>(_ClassXml_QNAME, ClassXmlType.class, null, value);
    }

}
