//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.18 at 02:08:56 PM IST 
//


package com.eca.cme.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ownerCntxElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ownerCntxElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="class-property-cnfg" type="{}classPropertyCnfgType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="class-trigger-actn-ref" type="{}classTriggerActnRefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="class-relation-ref" type="{}classRelationRefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="class-attribute-ref" type="{}classAttributeRefType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ownerCntxElementType", propOrder = {
    "classPropertyCnfg",
    "classTriggerActnRef",
    "classRelationRef",
    "classAttributeRef"
})
public class OwnerCntxElementType {

    @XmlElement(name = "class-property-cnfg")
    protected List<ClassPropertyCnfgType> classPropertyCnfg;
    @XmlElement(name = "class-trigger-actn-ref")
    protected List<ClassTriggerActnRefType> classTriggerActnRef;
    @XmlElement(name = "class-relation-ref")
    protected List<ClassRelationRefType> classRelationRef;
    @XmlElement(name = "class-attribute-ref")
    protected List<ClassAttributeRefType> classAttributeRef;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger id;

    /**
     * Gets the value of the classPropertyCnfg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classPropertyCnfg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassPropertyCnfg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassPropertyCnfgType }
     * 
     * 
     */
    public List<ClassPropertyCnfgType> getClassPropertyCnfg() {
        if (classPropertyCnfg == null) {
            classPropertyCnfg = new ArrayList<ClassPropertyCnfgType>();
        }
        return this.classPropertyCnfg;
    }

    /**
     * Gets the value of the classTriggerActnRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classTriggerActnRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassTriggerActnRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassTriggerActnRefType }
     * 
     * 
     */
    public List<ClassTriggerActnRefType> getClassTriggerActnRef() {
        if (classTriggerActnRef == null) {
            classTriggerActnRef = new ArrayList<ClassTriggerActnRefType>();
        }
        return this.classTriggerActnRef;
    }

    /**
     * Gets the value of the classRelationRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classRelationRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassRelationRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassRelationRefType }
     * 
     * 
     */
    public List<ClassRelationRefType> getClassRelationRef() {
        if (classRelationRef == null) {
            classRelationRef = new ArrayList<ClassRelationRefType>();
        }
        return this.classRelationRef;
    }

    /**
     * Gets the value of the classAttributeRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classAttributeRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassAttributeRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassAttributeRefType }
     * 
     * 
     */
    public List<ClassAttributeRefType> getClassAttributeRef() {
        if (classAttributeRef == null) {
            classAttributeRef = new ArrayList<ClassAttributeRefType>();
        }
        return this.classAttributeRef;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
